### ISSUE TITLE
Implement tower draining

### ISSUE THREAD

**Issue by SirLovi** [ScreepsOCS/screeps.behaviour-action-pattern#205]
I currently struggle with one pesky screeps player with really high defences (I.e. High walls, multiple towers, stocked storage).
The Melee-Healer creep horde was not able to punch through.
The most effective way of defeating that kind of advanced player would be ''Tower draining'' ( TOUGH creeps repeatedly entering the border of enemy room and after taking some healable damage, they step back to the neighbouring room to instantly get healed by healers waiting at the border, thus effectively draining his towers and storage of energy.)
After all his energy is wasted, the route is clear for the attack creeps to rampage.

**Comment by Animatrixy** [comment]
agree this is a problem i have faced as well, the melee and healer role needs combining i think first and then maybe implement some massive hit point creeps like you said to drain towers. The melee needs a bit of work anyway as they are not overly effective in defending, i have lost the last 4 rooms due to my melee creeps becoming overwhelmed and the way they sit on the ramparts even if being swarmed elsewhere is not the best at present, they should take the fight to the invader, i have tried to look at the code but as i am new to js i am still learning atm..

**Comment by SirLovi** [comment]
I have an idea how to make this work using a simple state-machine..
We would need two flags, one at each side of the room border.
Flag in the neutral/friendly room = Flag1
Flag in the enemy room = Flag2

Healers would gather at the Flag1 and wait for injured creep to arrive (No change in the healer behaviour would be needed apart from the new gathering point)
The TOUGH creep (Tank) would gather at the Flag2, if the Tank creep's health goes under certain level the creep switches action and goes to the Flag1.. Where it's healed -> If full health -> Go back to Flag2
Any better ideas? Could this work?

**Comment by cyberblast** [comment]
Hi, 

this is already adressed in issue #75. 
Please also have a look in the [military project](https://github.com/ScreepsGamers/screeps.behaviour-action-pattern/projects/6), (via the "Projects" tab above). I really believe #185 is quite important (add heal to melee & ranger)!

I think the proposed solution outline would work, but I'd prefer a flagless system if possible. 
Combat creeps having a small heal part can also heal everywhere, during combat and simply flee to neutral area (exit) to have some rest and restore to full life. 

A "teaser creep" should stay as near to the exit as possible, as far away from the tower as possible (more expensive for the tower). If the tower is only reacting at a shorter range the teaser creep will need to slowly aproach until hit...
