### ISSUE TITLE
November Roadmap

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#242]
Another month is passing. 
As usual, that means I will now have an eye if the code seems to be stable (no breaking bugs) and create a new release. 
I also created a new [milestone](https://github.com/ScreepsGamers/screeps.behaviour-action-pattern/milestone/6) and already added some issues I want to get rid of next. 

There are so many [topics](https://github.com/ScreepsGamers/screeps.behaviour-action-pattern/projects), so much to do. 
What would _you_ like to see implemented next? 
Some suggestions: 
- Harvest power
- Utilize labs
- Improve defensive and offensive capabilities (tower, combat, nuke)
- Core development (e.g. performance, spawning or task queue ...)
- Better reports & statistics
- Build automation
- Better documentation or instruction manual

Please keep in mind that we are currently tight on coding capabilities (mostly me). So we will have to focus on one topic at a time...

That being said, I'd also like to encourage everybody to also participate in coding. 
Don't be shy. A bad implementation proposal is at least always a good try and exercise. 

Please discuss what you think should be done next!

**Comment by ValkyrX** [comment]
So code looks good so far, however I have got quite sporadic spawning of warriors, also I think we need to get rid of mass attack as well because 7 of my warriors took on 3 lower spec rangers and lost because they kept running away ? I still think combat creeps need work tbh.. dunno what every9one else thinks

**Comment by cyberblast** [comment]
So what would you suggest? 
Not to use MassAttack? I'm unsure if it's that much of an issue. it only gets activated if there are at least 3 hostiles in range. But, sure, that could easily be turned off. We could experiment with its effectiveness... 
Anything else? Specific ideas how to improve it?

**Comment by Dasku** [comment]
For me I'd say the 3 things I look forward to most are, Harvest power, Utilize labs and Improve defensive and offensive capabilities. Maybe working on the creeps first? The new warriors seem great but I think they need more tough, or there needs to be a dedicated healer, or a tank of some kind to soak the damage and heal its self. I'm still pretty new so for me taking new (good rooms) is my biggest issue right now. Harvesting power looks good to get better creeps and get on the power leader-boards. And lab boosts would also be great but seems like the biggest thing to implement due to needing to transport minerals between rooms to make different boosts, huge amounts of distribution (if I understand it right). But it would be great to have boosts/better creeps. I'm still very much a beginner when it comes to coding and I'm doing courses so will try and contribute where I can. Might be able to add some of the stuff I've learnt into the instruction manual if that would help.

**Comment by SirLovi** [comment]
I am currently in a really comfortable position.. But there are a lot of cases where the effectivity could be improved:

- **Better privateer protection in exploited rooms**; I'm currently maintaining 1 defense flag per remote room, which is quite expensive (Maybe something like flag cloaking for defense/attack flags could help)

- **Implementing source keeper warriors and center rooms mining**; This would surely increase the net energy income by a lot

**Comment by cyberblast** [comment]
> there needs to be a dedicated healer 

We already have one, but yes, it's not spawning by default. Also requires a logic update. 

> a tank of some kind to soak the damage and heal its self 

Also a good Idea, but what then? When should they spawn? What should they do? 
I think the hardest problem with such a type is coordinated group behaviour. We need to ensure the tank is up front, followed by some rangers, then healer. Thats quite complicated. 

> Better privateer protection in exploited rooms; I'm currently maintaining 1 defense flag per remote room, which is quite expensive

Yes, I do it in the exactly same way. So you mean that issue #178 "Auto spawn defense for reserved or exploitation rooms"?

> Implementing source keeper warriors and center rooms mining

Its possible already, I tried it a while ago but it was too expensive (maybe a bit better now). To get this really working we need a specialized SK combat creep, which can kill a SK alone quite fast and keeps the room clean. I've already seen it. That's not the main problem. But there will occasional be bigger and boosted Invader gangs (up to 5). Its a new addition for the center rooms. I'm unsure how to handle that - without boosting. And I also don't know if its still profitable then.

**Comment by dkluempers** [comment]
Specialized SK combat creep would be great.  I have seen someone try and clear one of those rooms and it looks tough.  It looks like a mass attack or a coordinated attack between two owners might be something that work.  I will need to think some more on that.

**Comment by cyberblast** [comment]
You can see a good one in action [here](https://screeps.com/a/#!/room/E34S24)... 
He uses only one (unboosted) creep to handle the SKs. 
The trick is the body. Its measured to exactly kill one SK. The creep itself is not movable very soon, so its not a good invasion creep, but tailor-made for SKs.

**Comment by dkluempers** [comment]
Wow

**Comment by Dasku** [comment]
> Also a good Idea, but what then? When should they spawn? What should they do? 
Also requires something like an 'offensive gather point' to create the crew. Maybe "renewCreep", to have them all fresh, when starting, etc.


I think there is a couple options, I'm just not sure having the attack creeps heal themselves is the best way forward. 

In that same room you linked you can see his healer and warrior on the left too. But maybe the Move first instead of attack (like the SK minion) means you dont need tough so can take more attack or ranged attack. The healer will mean you will always be able to move after the fight. 

Specifically for tower draining you could have a new flag you put out side the room which will spawn a tank and 1-2 healers  the healers wait outside and the tank goes in and out to get healed. (using a second trigger flag inside for the tank). (if 2 can outheal a tower then they can all go inside, by moving the flag inside once they arrive,),

If we have a dedicated healer you could make them spawn 1:3 with the new warriors and take heal off them and add tough/more attack. With a swarm of 6 warriors and 3 healers you may be able to just rush a room without the need for draining first. This may need tuning to find the right ratio of healers to get past towers.  If the healers always flee enemy creeps and try to heal they should stay safe most of the time. 

The SK minion in that room is a great example I saw one just like it today in another room and would be great for the centre rooms.  

> I think the hardest problem with such a type is coordinated group behaviour. We need to ensure the tank is up front, followed by some rangers, then healer. Thats complicated. 

I think this is key and why healers might be the answer, if you can out heal the dmg everything can move with the same flag. As a group, whoever gets hit gets healed along the way. With the self healing warriors now they all heal each other but not quite enough. If you had more healers you may even only need 1-2 warriors.  

Coordinating them I'm not so sure about, maybe grouping a 'squad' so they can all follow the same path? or walk in a line (so the tank is always leading). Maybe healers have a designated creep to follow so then all the behaviour and control is done via 1 creep not all of them.
