### ISSUE TITLE
Creep statistics

### ISSUE THREAD

**Issue by erik-smit** [ScreepsOCS/screeps.behaviour-action-pattern#277]
I was curious about the efficiency of my privateers.

Would it make sense to keep statistics for creeps for their actions?

**Comment by erik-smit** [comment]
Example:

https://github.com/erik-smit/screeps.behaviour-action-pattern/commit/10f3767538e6cb1aae28f0328e122cb944eb398b

Generates:

```
[11:35:20 AM] privateer-1200-7 > Farewell! stats: {"energy":300}
```

**Comment by cyberblast** [comment]
Yes, a very good idea. There is also an issue for that #78 "Register energy spending". 

I'd maybe prefer a new Memory namespace for that. And we should think about it more general. Which data do we need => how do we need to design/store it. 
We could also generate charts etc. using the stored data. etc..

**Comment by erik-smit** [comment]
I guess it depends on what kind of datas you'd like to collect.

For me, I'd say it sounds sensible to store creep-specific statistics 'near' or 'in' the creep.
Just like target, action, etc.

If not, what do you propose?

**Comment by cyberblast** [comment]
If we store data at the creeps memory it will vanish once the creep dies. If we are only interested in data about the current population that would still be possible. But for evaluation and calculation on this data we would need to collect it from each creeps memory. I don't think we need evaluations for a certain single creep. 

I could imagine a lot. A lot of different charts and KPIs. All quite interesting, but a lot of work, cpu and memory. 

The first point we need to clarify is: 
What do we NEED? Which questions do we have that we want to answer by storing and evaluating that data. 

Possible evaluations could be: 
* Amount (absolute/relative) of energy spent into upgrading/spawning etc. by time/ticks
* Amount of energy harvested per room/creepType/source
* avg. price per mineral
etc... 

Most of those charts would be interesting. I guess only a few are really fundamental. 
Once we know what we need/want, we can plan how we need to design data storage. 

In general we should try to design it in a most reusable/extendable way. That's why I'd prefer storing it at a separate place.

**Comment by erik-smit** [comment]
If we store data at the creeps memory it will vanish once the creep dies.

For my current goal "how much energy did the privateer store vs. how much did it cost to spawn", this would not be a problem.

**Comment by cyberblast** [comment]
yes, but I try to follow a larger goal. 

I think the evaluation you are about to make is interesting. And I'm eager to see its results. But I'm unsure if we'll need that in the repo for "always" and "everyone". 
I'd prefer to see this as a one time study. collecting data, evaluating it. conclude something. 

Or how do you think about it?

**Comment by erik-smit** [comment]
I don't know.
I see it as part of the 'health' of the colony.
I imagine I could be spawning too many privateers, or some mechanism is preventing them from being efficient.
Or for instance, I change creep.behaviour.privateer to calculate flagDistance from creep instead of from controller and I want to know if this change makes my privateers more or less efficient.

**Comment by cyberblast** [comment]
I think we will change the whole privateer system anyway soon. 

Another option would be a pluggable module.

**Comment by erik-smit** [comment]
Would that require copying the functions getting replaced, and adding the stats to it?

**Comment by cyberblast** [comment]
yes. those functions which need a change would be defined in the module and overwritten.

**Comment by Dasku** [comment]
I like this idea a lot. I'm obsessed with efficiency. Maybe not something that's always on for cpu reasons, but a module or feature you can turn on/off would be great. Knowing a creeps value, (i.e. energy moved/mined/used vs cost to spawn) would be a great indicator to use when working on improving other creeps like the Pirvateers, we can test which version/change/improvement's give the most value increases. This may also not be great for each individual creep, you may want an average over 5 creeps or 24 hours or something like that to run tests with. This could then be used to test things like should privateers choose a new task based on range from current location or home room?

I think this is much more about the energy/mineral economy and efficiency. I don't think it would have too much use for fighting creeps would it? Maybe when testing SK creeps etc.

Currently my only way to track my colony efficiency is my energy mined per hour - creep costs from the overview.

**Comment by erik-smit** [comment]
I don't think this counting will use any significant CPU.
In fact, I could imagine that logic to determine which creeps to keep score and which not might be a more expensive operation than the counting itself.

Also, I currently count it in the storing action handler, so fighting creepings aren't affected by it.

For reference:
[4:59:16 PM]privateer-1200-2 > Farewell! stats: {"energy":3300}

Currently, my 1200 energy sized privateers collect 2700-3300 energy per lifetime.

**Comment by Dasku** [comment]
Are these adjacent rooms? I'd be interested by how much the collected figure drops for rooms at 2 and 3 range if you know?

**Comment by erik-smit** [comment]
3 adjacent rooms with 2, 2, and 1 energy source each, and 1 non-adjacent with 1 energy source.

Privateers aren't allocated to a specfic room, so I don't know how much a privateer would do at specific ranges.

**Comment by ledelec** [comment]
Hello Erik, sorry of posting message wrong place here but I didn't find any contact info about you. I have simple question about Sony API example you made. Could you please contact me: linnar.edesi@gmail.com. Thanks!

**Comment by Methel** [comment]
Might be too heavy for what you want, and its specifically for Privateers  But you could pretty easily check if each "trip" is paying off and how much. 
Lets define each trip as from the point where the creep gets the order to move to a source, to the moment it drops off the energy. 
You can then take amount of ticks spent, creep cost and plug those into:

energy deposited - (creep spawn cost / 1500 * trip time)

**Comment by jisaf** [comment]
I started working on some reporting for this last night.

I hook into every time a remoteHauler puts energy into something, store it in a new memory object called longTermStats (so it doesn't get wiped on the statistic cycle) as:

flag : {
  total: <number>,
  weight: <number>,
  creeps: {
    1700-fasG342FSdf235Gf: <number>,
    1200-ghjy657ghj546756y: <number
  }
}

total is a running count of all amounts deposited (i.e. the room the flag is in has provided that much)

weight is the total weight of all creeps reporting in for that flag. It happens when they dump, not when they are born, and I will probably change that.

The creeps are named weight-id and it's mostly just to see what weight the creep cost compared to what they delivered home to me before kicking the bucket.

This gets included in the stats email similar to this:
flagPerformance
  Flag4 total deposited: 9377 at an ROI of approx 552% 
  Flag3 total deposited: 16569 at an ROI of approx 316% 
  Flag1 total deposited: 15252 at an ROI of approx 291% 

I also have a command line function to reset the stats when needed (I just switched from 2 haulers per source to 1 and want to see the difference).

It doesn't include the cost of reservers or miners, but those are close to standard minus ~50 ticks of life per additional room (I think)

My code is/will continue to be ugly, but I'm happy to keep working on it and submit a PR in a few days when it's less embarrassing if others want it.
