### ISSUE TITLE
Performance Analysis

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#318]
_From @Dasku on November 8, 2016 20:48_

Implement profiling tool etc

_Copied from original issue: cyberblast/screeps.ocs.internal#10_

**Comment by chobobobo** [comment]
There is rudimentary profiling now in the feature/profiling branch, essentially saving CPU usage and comparing after to see if it is above a given limit.  It is enabled by setting     PROFILE: true in your viral.parameters.  It helps for chasing down significant CPU increases, but it would be improved by tracking the CPU usage of different core areas as a percentage of the total CPU usage rather than crossing a certain threshold.

**Comment by chobobobo** [comment]
Profiling has now bee implemented and merged.
