### ISSUE TITLE
Worker/Pioneer picking/uncharging prio's

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#386]
Priorities are:
>        let priority;
>        if( creep.carry.energy == 0 ) {
>            priority = [
>                Creep.action.picking,
>                Creep.action.dismantling,
>                Creep.action.withdrawing,
>                Creep.action.uncharging,
>                Creep.action.harvesting,
>                Creep.action.reallocating,
>                Creep.action.idle];
>        }

However I noticed today that a pioneer travelled to the miner, picked up 94/300 energy, ignored the full container, then travelled back to fill extensions etc. 

I realise if we had a check to say "unless you have 50% energy, get some more" it would mean they would go collect more energy before they had used all their energy being carried, however could we add   a followup action to Picking action, which says, "if any more energy within 1-2 squares and my energy < 50%, grab that too before leaving"?

**Comment by whardeman** [comment]
@Dasku I really like this. 20 on the ground getting picked up and 2000 in a nearby container getting ignored has bothered me for a while.

A creep can only "pickup" once per tick, right? So, maybe just doing the check after pickup and pre-targeting another nearby structure (container/link/storage) before the creep's next loop? I'm still new to the newTarget/nextAction stuff. Just spitballing here.

**Comment by cyberblast** [comment]
hmm currently it's only 
`if( creep.carry.energy == 0 )`
we could very easily change that to 
`if( creep.carry.energy < creep.carryCapacity*0.5 )` 
so that it will always take more energy until at least at 50%. 
Searching for "the nearest energy" would require a lot of calculation. We would need to cover a lot of cases .. dropped, container, source, storage or dismantle flags... then choose the right action for the given target.
