### ISSUE TITLE
Mineral worth and picking priority

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#443]
I know we don't have boosting or labs yet but how valuable are minerals? 

Currently invaders drop a lot of pre made minerals when they die in our rooms, most of the time the minerals disapear before they are picked up.

Would it be worth having a picking minerals as higher priority for workers, haulers and privateers? This way we could collect much more of the dropped minerals in preparation for getting labs.

**Comment by cyberblast** [comment]
* Worker 

Worker have picking as highest priority already. 

* Hauler 

We also had a recent discussion if picking should be an even lower priority for the hauler #412. 
I think it should stay as it is. 

* Privateer 

Current priorities for remote rooms: 
![image](https://cloud.githubusercontent.com/assets/20269868/21748846/2e5620bc-d590-11e6-9a7e-987f79ac168b.png)
That may get adjusted. But there are a lot of corner cases which are not handled yet. Because privateers are used as well (currently) to dismantle walls. And there is no check (currently) if the resource to pickup is behind an enemy wall and not reachable.

**Comment by Dasku** [comment]
Hmm yeah. Would it be worth allowing privateers to pick from a homeRoom before travelling? Is that "worth" more than travelling to another room to exploit?

**Comment by cyberblast** [comment]
>  Is that "worth" more than travelling to another room to exploit? 

Personally I'd say no. I think it's the workers/haulers job. otherwise the privateers would start helping with hauling energy from dropmining in your room.

**Comment by Dasku** [comment]
Good point, I'll close this then
