### ISSUE TITLE
Better Room Selection function

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#483]
add options : 
* minRCL
* maxRange
* minAvailableEnergy
* maxQueuedCreeps
* custom callback
* only include rooms "alive" (e.g. having a miner and a hauler or worker > 4)

**Comment by Dasku** [comment]
I don't know if it fit's into this, but could we use a way of including a calculation for total body parts required divided by actual distance for that source. So for remote haulers, they could spawn multiple small haulers reducing to 1 hauler of the exact size required to haul the right amount of energy for the distance.  Based on the exact distance for each source. This could then also be used for privateers at lower levels.

**Comment by Dasku** [comment]
Also maybe a way to block a specific room (say the room the flag is in for pioneers and a high level room died)

**Comment by cyberblast** [comment]
> could we use a way of including a calculation for total body parts required divided by actual distance for that source 

hmm. that would be possible if the room had only 1 spawn. if it has two you can't know which one is going to spawn. so you can't get an *exact* distance. 
Also, this calculation would need to be done *after* room selection, in an other function. 

> Also maybe a way to block a specific room (say the room the flag is in for pioneers and a high level room died) 

hmm, we could include a check to only include rooms which are still "alive". I'll add that to the specification above.

**Comment by Dasku** [comment]
I'd imagine most people have their spawns fairly close? Maybe just use the distance of the store not the spawn? Thats where they drop the energy (not including times they get to use a link)

**Comment by Dasku** [comment]
for a set distance of 50 for your homeRoom + the real distance of travel outside.

**Comment by cyberblast** [comment]
hmm. yes I think an *exact* measure will never be possible. Also due to the options to deliver energy to different places (containers, links, storage...). 
I think Storage or '25' (middle of the room) would be possible

**Comment by karlthepagan** [comment]
maxQueueTime - sum of body parts * 3 divided by number of spawns, seems more useful than just the queue depth

**Comment by karlthepagan** [comment]
forSetup - provide the setup spec to the API... yeah seems odd, but you can filter a lot of things centrally based on that

1. I would start by excluding any predictedRenewals for the room's miners and haulers which would be eclipsed by the spawn.

2. Each task should have a callback to calculate their predictedRenewal needs. It would also be nice for the room to get a callback when a spawn is scheduled which will overlap those needs so that it can shift spawns earlier or later. This is actually a very complex problem to get to production so maybe you can put it in the "mad scientist file" for later ;)
