### ISSUE TITLE
Task.spawn should be a priority queue. Reservers spawn before Miners.

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#507]
At a base level it makes no sense that reservers should spawn before miners. This is addressable by adding a priority number to the entries in the Task.spawn call (default zero?)

**Comment by cyberblast** [comment]
But the reserver may get spawned in an other room than the miner. Maybe in at the same time, regardless of their priority (if queued at the same time). Or the higher priorized may even get spawned later, because something else (with an even higher priority) gets queued in that room. Nobody can predict that. 

If we want to ensure a creep gets spawned after an other, we maybe shouldn't queue it at all until we want it to get spawned. 

But adding some more flexibility to the queue seems to be a good idea in general.

**Comment by karlthepagan** [comment]
the current "setup queue" (even without that feature branch) is effectively a priority queue. Having those numbers is really helpful.

**Comment by TafThorne** [comment]
I think we should consider the RFC2119 https://www.ietf.org/rfc/rfc2119.txt defintions of _Should_, _Must_ and _May_.  Then use the phrase:
Miners should spawn before reservers.  Reservers may be spawned at the same time as miner but in another room or spawn.  

What we must ensure is that rooms only exploit the rooms marked for exploitation that are closest to them.  Rooms must not exploit a room that is closer to another owned room of level 4 or higher.  Rooms may reserve rooms that are marked for exploitation but are not closer to them than another owned room.  


All of that would help with my problems in #525 where it seems that my weaker room is pumping out reservers but then has not got enough energy to generate privateers to export the target rooms.  Instead a stronger room of mine is sending out privateers and picking the room clean.

**Comment by cyberblast** [comment]
Actually I am aiming for a more variable system. 

Currently, privateers and haulers will carry energy always back to the room where they have spawned. 
But thats not required. 

It's one question which room should spawn (a privateer, remoteMiner, remoteX). This should be a "rich" one. 
It's an other question where that energy should go to. That should be a "poor" one. 

The challenging point with this is calculating the required hauler volume. Which is easier for a fixed route. Or we "temporarily" fix it each time we are spawning a new hauler, calculating the "best room in range requiring energy" and recalculating resulting hauler requirements...

**Comment by cyberblast** [comment]
> you need to be aware of the balance of energy in the room 

Thats explicitly an integral part of the plan

>  it could spawn creeps and give them to another room 

That's not part of the plan

**Comment by karlthepagan** [comment]
> it could spawn creeps and give them to another room

easily implemented using `Creep.spawningStarted.on` callbacks (save the creep name in your queue)

**Comment by chobobobo** [comment]
I believe this is no longer relevant as miners spawn with medium priority and reservers only spawn if there are enough haulers to haul.  Also, @karlthepagan I believe you have since cast off your childish notions of the spawn queues https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/343

**Comment by karlthepagan** [comment]
:+1:
