### ISSUE TITLE
behaviour.upgrader crash with multiple in-range containers

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#541]
Unable to determine working location for upgrader in room E49N82

workaround: poke `determinatedSpot = {x:24,y:9}`

**Comment by karlthepagan** [comment]
Might have also been the container at 23,6 was qualified for mining as well as upgrading.

**Comment by karlthepagan** [comment]
That's definitely the case. I have moved the cause of this error and new upgraders are functioning properly.

**Comment by cyberblast** [comment]
> Might have also been the container at 23,6 was qualified for mining as well as upgrading. 

Yes. a container at E49N82:23,6 would be considered for both, mining and upgrading. Which is not the problem. Those containers are supported in general. 
The problem is: you upgraders will try to find a spot where they can reach all containers and links associated with that controller. 
So instead you could build a container at E49N82:23,6, and move the container at E49N82:25,10 to E49N82:24,7. This way both would be reachable.

**Comment by cyberblast** [comment]
by design. 
There could be a change in position selection. 
But I think we should postpone that as it shouldn't be *required* but nice to have. And the list of important issues is growing...
