### ISSUE TITLE
Change Manual Move Command to Work With Macros

### ISSUE THREAD

**Issue by torin555** [ScreepsOCS/screeps.behaviour-action-pattern#576]
Can we change the manual movement command to use the object ID of the creep instead of the name so we can use it with the CLI macro system in screeps?

**Comment by cyberblast** [comment]
What exactly do you mean? 

> the manual movement command 

You mean the hint in commands.js? There is nothing custom with `Game.creeps['<creepName>'].move(RIGHT);`, 100% original screeps API and CLI compatible. 

Instead of selecting a creep by it's name, you can get any object by it's id using `Game.getObjectById('<anyId>')`. So you can use `Game.getObjectById('<anyId>').move(RIGHT)` as well.

> the CLI macro system in screeps 

?

**Comment by karlthepagan** [comment]
These macros are probably part of this chrome extension : https://github.com/stybbe/Screeps-SC

**Comment by torin555** [comment]
Ah, yeah that explains it. They're in Screeps SC. It adds two buttons to the console:
![image](https://cloud.githubusercontent.com/assets/2602862/22176231/c602f5b6-dfc2-11e6-87f1-0a2d40032fbd.png)

**Comment by cyberblast** [comment]
oh, yes, sorry. never used it ^^
