### ISSUE TITLE
Planned Structures with Flags

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#672]
The idea is to have flags representing specific structures, so you can build them once your RCL increases automatically.

This would ideally run on a long loop, configured in the parameters.

Possibly have another parameter to keep the flag. Downsides to keeping the flag would be wasted CPU, however an upside would be able to recreate the structure if it decays/gets destroyed. Default would be false.

Thoughts? Ideas?

**Comment by karlthepagan** [comment]
One thing I've been microing (that I should stop doing manually) is spawning extra workers when I'm close to RCL increases. I think this is something that we could trigger at a specific number of ticks before RCL-ing.

**Comment by Kelturio** [comment]
something like this ? https://github.com/tanjera/screeps/blob/master/blueprint.js

**Comment by jisaf** [comment]
What if you set a flag, it laid out the proposed construction with the Visual API, save the location into a memory location that is accessed only on the RCL increase, then removed the flag(s) saving on CPU.

I also don't know if you want to have a long loop because it's either way too long (early levels) or way too short (later levels) - could you calculate an estimated tick of completion of your RCL (3 check points 500 ticks apart to average out your upgrading), then do a check at the mid point (are you where you expected, if so return, otherwise run another estimate and repeat).

If you're always doing this mid point check, you'll rarely check early on in the cycle, but check frequently as you approach completion so you build very quickly on completion.

The mid point check could be configurable so it checks more frequently or less frequently depending on your CPU desires.

And then you could also build anything else off of this one level check:
 Build stuff on RCL upgrade
 Spawn stuff 5000 ticks before upgrade
 Invade 10000 ticks after upgrade etc.

Just a few thoughts. I'd love to trigger things on RCL upgrade.

**Comment by Spedwards** [comment]
Implemented.
