### ISSUE TITLE
Safe Mode When You Are Getting Attacked

### ISSUE THREAD

**Issue by SEATURTLEKING** [ScreepsOCS/screeps.behaviour-action-pattern#878]
One of my old codes had a thing where if there was an invader and the tower ran out of energy and there are no defenders left, the room would automatically be put on safe mode. That would be cool if the code did that.

**Comment by torin555** [comment]
Yeah this has been proposed in the past, it's a possibility but automatic safe mode does present some possible issues.

**Comment by Dasku** [comment]
As @torin555 said this has been mentioned and discussed a few times before (https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/166 )

I think the real issue here is each players idea of what situation constitutes a good time to trigger safe mode. I'm not totally against a basic safemode trigger being implemented but it should be very parameterised: On/off, number of creeps required to trigger, must be player and not NPC, only trigger when a wall or rampart is destroyed?

Many things to consider so it doesn't impact people who don't want to use it. Personally I like the email notifications, I've never used any safemodes, I see them as very valuable for real attacks from players and I would not want to automate there use in fear of wasting one.

**Comment by karlthepagan** [comment]
The safe mode cool down leaves you vulnerable for almost 2 days. Let me show you how to add the viral for this.

**Comment by karlthepagan** [comment]
Parameters is not well suited for anything that only a few players will use.

If you want automatic safemode, put it in the extensions / virals.

Here's how you do that: add `viral.room.js` to your code with these contents:

```
let mod = {};
module.exports = mod;
mod.analyze = function() {
    this.baseOf.viral.analyze();
    
    for (const roomName in Game.rooms) {
        // safemode code goes here
    }
};
```

When that's done execute `getPath('room', true)` in the console to invalidate the code caching and load the new extension. Now you can edit the viral and put whatever code you want in there, it will execute the original analyze code and then your code.

**Comment by torin555** [comment]
@Spedwards It's an idea, but I think for the moment we have a lot of pressing issues that should be dealt with first

**Comment by Spedwards** [comment]
Don't have to tell me. May be worth a new, fresh issue. But even then, extremely low priority in comparison to other things going on.
